# Generated by Django 4.1.7 on 2023-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_hours',
            name='active_dtime',
        ),
        migrations.RemoveField(
            model_name='login_hours',
            name='locked_dtime',
        ),
        migrations.RemoveField(
            model_name='login_hours',
            name='total_session_dtime',
        ),
        migrations.AlterField(
            model_name='leave',
            name='casual_leave',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
