# Generated by Django 4.1.7 on 2023-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_remove_login_hours_active_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_hours',
            name='active_time',
            field=models.CharField(default='00:00:00', max_length=50),
        ),
    ]
