# Generated by Django 4.1.7 on 2023-09-22 17:05

from django.db import migrations, models
import employee_information.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_alter_login_hours_break_end_dtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_personal',
            name='employee_ID',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='login_hours',
            name='break_end_dtime',
            field=models.DateTimeField(default=employee_information.models.default_start_time, null=True),
        ),
        migrations.AlterField(
            model_name='login_hours',
            name='break_start_dtime',
            field=models.DateTimeField(default=employee_information.models.default_start_time, null=True),
        ),
    ]
