# Generated by Django 4.1.7 on 2023-09-26 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_remove_employee_education_diploma_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITHelpDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.TextField()),
                ('issue_description', models.CharField(max_length=500)),
                ('priority', models.TextField()),
                ('to_send_email', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
