# Generated by Django 4.1.7 on 2023-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_ithelpdesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_hours',
            name='break_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='login_hours',
            name='session_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
