# Generated by Django 4.1.7 on 2023-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0013_alter_login_hours_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_hours',
            name='break_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='login_hours',
            name='session_time',
            field=models.TimeField(null=True),
        ),
    ]
