# Generated by Django 4.1.7 on 2023-09-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0017_alter_login_hours_active_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_Hours',
        ),
    ]
