# Generated by Django 4.1.7 on 2023-09-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0019_login_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_Hours',
            new_name='Login_Hour',
        ),
    ]
