# Generated by Django 4.1.7 on 2023-09-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0020_rename_login_hours_login_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('login_dtime', models.DateTimeField(null=True)),
                ('logout_dtime', models.DateTimeField(null=True)),
                ('break_start_dtime', models.DateTimeField(null=True)),
                ('break_end_dtime', models.DateTimeField(null=True)),
                ('session_time', models.DateTimeField(null=True)),
                ('break_time', models.DateTimeField(null=True)),
                ('active_time', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employee_personal')),
            ],
        ),
        migrations.DeleteModel(
            name='Login_Hour',
        ),
    ]
