# Generated by Django 4.1.7 on 2023-09-27 16:44

from django.db import migrations, models
import django.db.models.deletion
import employee_information.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0021_login_details_delete_login_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateTimeField(null=True)),
                ('login_dtime', models.DateTimeField(null=True)),
                ('logout_dtime', models.DateTimeField(null=True)),
                ('break_start_dtime', models.DateTimeField(default=employee_information.models.default_start_time, null=True)),
                ('break_end_dtime', models.DateTimeField(default=employee_information.models.default_start_time, null=True)),
                ('session_time', models.TimeField(null=True)),
                ('break_time', models.TimeField(null=True)),
                ('active_time', models.CharField(max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employee_personal')),
            ],
        ),
    ]
