# Generated by Django 4.1.7 on 2023-09-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0022_login_hour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_Hour',
            new_name='Login_Hours',
        ),
    ]
