# Generated by Django 4.1.7 on 2023-09-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0023_rename_login_hour_login_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_hours',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Login_Details',
        ),
        migrations.DeleteModel(
            name='Login_Hours',
        ),
    ]
