# Generated by Django 4.1.7 on 2023-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0027_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_hours',
            name='active_time',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
