# Generated by Django 4.1.7 on 2023-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0028_alter_login_hours_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_hours',
            name='active_time',
            field=models.CharField(max_length=100),
        ),
    ]
