# Generated by Django 4.1.7 on 2023-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0031_alter_employee_personal_phone_employeeloginhrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='ctc',
            field=models.FloatField(default=30000),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross',
            field=models.FloatField(default=30000),
        ),
        migrations.AddField(
            model_name='salary',
            name='payable_days',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='uan_no',
            field=models.FloatField(default=101731461799),
        ),
    ]
