# Generated by Django 4.1.7 on 2023-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0032_salary_ctc_salary_gross_salary_payable_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='other',
            field=models.FloatField(default=40000),
        ),
    ]
